

# [[imports]]
#     path = "github.com/CaiJimmy/hugo-theme-stack/v4"


# config/_default/module.toml
theme = "hugo-theme-stack"

# [module]
#   [[module.mounts]]
#     source = "themes/hugo-theme-stack/layouts/_shortcodes"
#     target = "layouts/shortcodes"
#   [[module.mounts]]
#     source = "themes/hugo-theme-stack/assets"
#     target = "assets"