name               = "hugo-stack"
compatibility_date = "2026-01-25"

[build]
    command = "chmod a+x ./.ci/build.sh && ./.ci/build.sh"

[assets]
    directory          = "public"
    not_found_handling = "404-page"
